# Welcome to Jekyll!

email: info@realitydevices.au

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
locale                  :     en-AU
title                   :     Reality Devices
description: >- # this means to ignore newlines until "baseurl:"
  Discover limitless possibilities with Reality Devices.
  Expert data consulting, specializing in rapid ideation and transformative solutions.
  Elevate your business with us, where data shapes success.
url                     :     
words_per_minute        :     200
timezone                :     Australia/Brisbane

# SEO
og_image                :     #default[author.avatar (see below)] or [github-avatar]
twitter_site            :     realitydevices
author:
  name                  :     Reality Devices
  avatar                :     https://github.com/realitydevices.png
  location              :     Brisbane, Australia
  links:
    - url:  https://x.com/realitydevices #A link or email: https://twitter.com/jack, mail@example.com
      icon: fab x-twitter # A Fontawesome code: fab fa-twitter - see https://fontawesome.com/
      label: X # A Label for the icon: Twitter
    - url:  https://www.instagram.com/realitydevices # Another link
      icon: fab instagram # Another FontAwesome code
      label: Insta # Another label

fa_version: 6 #default ["6"] Use 6 or 5
gtag_id                 : AW-11380611459

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/
search:
  provider              : google #Select a provider for enable search: lunr, algolia, google
  label                 :  #default ["Search"] Text on navbar when search is enabled
  landing_page          :  #default ["/search"] Link on navbar
  #lunr_maxwords         :  #default [30] lunr only - May slow down your site build
  #algolia_logo          :  true #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.
#https://cse.google.com/cse.js?cx=b602ffde2a4cb42b4
google_cse_id: https://cse.google.com/cse?cx=b602ffde2a4cb42b4 #b602ffde2a4cb42b4


# B. Navigation
# Configure your navbar and the footer of your site

# Navbar:
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  "dual" #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  Reality Devices # Title in navbar
    url     :  / # default["url/baseurl"]
    img     :  # An small image, try 30x30px
  nav:
  - title   : About # Label
    url     : /about # url
  - title   : Contact
    url     : /contact


footer:
  links:
    - label: "X"
      icon: "fab fa-x-twitter"
      url:  https://x.com/realitydevices
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: https://www.instagram/realitydevices


# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

# Theme and colors
chulapa-skin:
  highlight:  # default["default"]
  skin:  preptor # Optional predefined skins
  autothemer: true  # Bool: Use autotheming
  vars:
    primary: "#00d4f0ff" #default ["#007bff"] - Bootstrap blue
    secondary: "#7c5d45ff"
    light: "#eaf4f5ff"



# Build settings
remote_theme: dieghernan/chulapa
plugins:
  - jekyll-feed
  - jekyll-include-cache

header_pages:
  - about.md
  - contact.md

repository: realitydevices/realitydevices.github.io
